# Generated by Django 4.1.7 on 2023-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='service/photo/', verbose_name='Фотография')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Время создание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начать')),
                ('end', models.DateTimeField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
